server:
  port: 8082

ms1:
  base-url: http://localhost:8081

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      libraryMs1:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
